# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks:

# Setup
title:               escapology done wrong
tagline:             'ein Ausbruchsversuch'
description:         ''
url:                 
baseurl:             'https://h0pkins.github.io'
paginate:            5

# About/contact
author:
  name:              Hopkins
  url:               
  email:             h0pkins@mailbox.org

# Custom vars
version:             1.0.0
